/**
 * Token Normalizer — Pre-clustering token sequence transformation pipeline.
 *
 * ## Purpose
 *
 * Addresses tokenization mismatches between parser output and ground truth
 * expectations. Some datasets (e.g., Proxifier) have Ground Truth templates
 * generated by non-standard tokenizers that produce different token granularity
 * than standard whitespace splitting. This module provides a pluggable pipeline
 * to normalize token sequences BEFORE Drain clustering.
 *
 * ## Architecture
 *
 * The TokenNormalizer is a Strategy pattern applied to token sequences:
 * - **Interface**: `TokenNormalizer` — a single `normalize` method
 * - **Pipeline**: `TokenNormalizerPipeline` — chains multiple normalizers
 * - **Built-in**: `AdjacentConstantFusion` — auto-detects and fuses constant pairs
 *
 * ## Why Pre-Clustering?
 *
 * The research-backed insight (validated against Loghub-2.0 benchmark and
 * logpai/logparser analysis) is that tokenization mismatches are a
 * **pre-clustering** problem, not a template creation problem:
 *
 * - LogSig (0.967 Proxifier GA): Uses term PAIRS — position-independent,
 *   length-independent matching. Completely sidesteps token count issue.
 * - LogCluster (0.951 Proxifier GA): Uses frequency-based clustering.
 * - Drain (0.527 Proxifier GA): Position-dependent, fixed-length. Cannot
 *   group messages with different token counts.
 *
 * Drain's fixed-depth prefix tree requires same-length messages to be routed
 * to the same branch. When the GT expects messages of different token counts
 * to be in the same group, token-level normalization is the only viable
 * approach without changing the core algorithm.
 *
 * ## Generic, Not Proxifier-Specific
 *
 * `AdjacentConstantFusion` makes ZERO assumptions about specific token values.
 * It only checks two universal properties:
 * 1. Both tokens are constant across ALL same-length messages
 * 2. Both tokens are "content words" (purely alphabetic, no punctuation, no params)
 *
 * These properties apply to ANY dataset where compound terms are consistently
 * adjacent in the token stream. The normalizer auto-detects which pairs to fuse.
 *
 * @module TokenNormalizer
 */

// ============================================================
// Core Types
// ============================================================

/**
 * Result of a token normalization operation.
 */
export interface NormalizationResult {
  /** The normalized token sequence */
  readonly tokens: readonly string[];
  /** Human-readable description of what was changed (for debugging) */
  readonly changes: string[];
}

/**
 * Pre-clustering token normalizer.
 *
 * Implementations can:
 * - Fuse adjacent tokens into compound tokens
 * - Split compound tokens into sub-tokens
 * - Add, remove, or reorder tokens
 * - Apply dataset-specific normalization rules
 */
export interface TokenNormalizer {
  /** Unique name for identification and debugging */
  readonly name: string;

  /**
   * Optional learning phase.
   *
   * Called once before processing a batch of messages. The normalizer
   * can analyze the batch to learn patterns (e.g., which adjacent tokens
   * should be fused).
   *
   * @param messages - Tokenized messages in the batch
   */
  learn?(messages: readonly (readonly string[])[]): void;

  /**
   * Normalize a single token sequence.
   *
   * Called for each message before Drain clustering. The normalized
   * sequence replaces the original for all subsequent processing.
   *
   * @param tokens - The tokenized message
   * @param paramStr - The parameter placeholder (e.g., "<*>")
   * @returns Normalization result with transformed tokens
   */
  normalize(
    tokens: readonly string[],
    paramStr: string,
  ): NormalizationResult;
}

// ============================================================
// Token Normalizer Pipeline
// ============================================================

/**
 * Pipeline of token normalizers, applied in registration order.
 *
 * Normalizers are applied sequentially: the output of one normalizer
 * becomes the input of the next. The `learn` phase is propagated to
 * all registered normalizers.
 */
export class TokenNormalizerPipeline {
  private normalizers: TokenNormalizer[] = [];

  /**
   * Registers a normalizer in the pipeline.
   *
   * @param normalizer - The normalizer to add
   * @returns this (fluent API)
   */
  register(normalizer: TokenNormalizer): this {
    this.normalizers.push(normalizer);
    return this;
  }

  /**
   * Registers multiple normalizers at once.
   */
  registerAll(normalizers: readonly TokenNormalizer[]): this {
    for (const n of normalizers) {
      this.register(n);
    }
    return this;
  }

  /**
   * Learning phase — propagates to all registered normalizers.
   */
  learn(messages: readonly (readonly string[])[]): void {
    for (const n of this.normalizers) {
      n.learn?.(messages);
    }
  }

  /**
   * Applies all normalizers in sequence to a token sequence.
   */
  normalize(
    tokens: readonly string[],
    paramStr: string,
  ): NormalizationResult {
    let current = tokens;
    const allChanges: string[] = [];

    for (const normalizer of this.normalizers) {
      const result = normalizer.normalize(current, paramStr);
      current = result.tokens;
      allChanges.push(
        ...result.changes.map(
          (c) => `[${normalizer.name}] ${c}`,
        ),
      );
    }

    return { tokens: current, changes: allChanges };
  }

  /**
   * Whether the pipeline has any registered normalizers.
   */
  get isEmpty(): boolean {
    return this.normalizers.length === 0;
  }

  /**
   * Number of registered normalizers.
   */
  get size(): number {
    return this.normalizers.length;
  }
}

// ============================================================
// Built-in: Regex Substitution (AEL-style aggressive preprocessing)
// ============================================================

/**
 * Replaces matched patterns with a substitution string in each token.
 *
 * Inspired by AEL's aggressive regex preprocessing: instead of wrapping
 * variable parts in masks, this fully REPLACES them with the paramStr.
 * This normalizes token counts by making all parameters the same length.
 *
 * ## Example: AEL-style number/IP replacement
 *
 * Input: ["192.168.1.1", "user", "123", "logged"]
 * Pattern: "\\d+" → replacement: "<*>"
 * Output: ["<*>", "user", "<*>", "logged"]
 *
 * ## Difference from Masking
 *
 * Masking wraps: "192.168.1.1" → "<IP>" (token count unchanged)
 * Substitution: "192.168.1.1" → "<*>" (token count still 1, but paramStr)
 *
 * The key advantage is that substitution normalizes the PARAMETER
 * representation, making param_count tracking consistent for
 * multi-dimension binning.
 */
export class RegexSubstitutionNormalizer implements TokenNormalizer {
  readonly name = "regex-substitution";

  /**
   * @param patterns - Regex patterns and replacement strings
   * @param replacement - Where to insert the substitution (default: "token")
   */
  constructor(
    private readonly patterns: ReadonlyArray<{
      /** Regex pattern to match in each token */
      readonly regex: RegExp;
      /** Replacement for matched content (use paramStr placeholder for param) */
      readonly replacement: string;
    }>,
  ) {}

  // Stateless — no learn phase needed

  normalize(
    tokens: readonly string[],
    paramStr: string,
  ): NormalizationResult {
    const result: string[] = [];
    const changes: string[] = [];

    for (const token of tokens) {
      let transformed = token;
      for (const { regex, replacement } of this.patterns) {
        const finalReplacement = replacement.replace(
          /\$\{paramStr\}/g,
          paramStr,
        );
        const before = transformed;
        transformed = transformed.replace(regex, finalReplacement);
        if (before !== transformed) {
          changes.push(
            `substituted "${before}" → "${transformed}" (pattern: ${regex.source})`,
          );
        }
      }
      result.push(transformed);
    }

    return { tokens: result, changes };
  }
}

/**
 * Collapses adjacent token groups matching regex patterns.
 *
 * Joins tokens into a temporary string, applies regex transformations,
 * and splits back into tokens. Useful for normalizing known optional
 * structures before applying AdjacentConstantFusion.
 *
 * ## Example: Proxifier KB parentheticals
 *
 * Input: ["bytes", "(18.4", "KB)", "sent"]
 * Pattern: match "(\\d+\\.\\d+\\s+KB\\)" → replace with ""
 * Output: ["bytes", "sent"]  (ready for AdjacentConstantFusion)
 *
 * ## Generic Design
 *
 * Patterns are specified as {regex, replacement} pairs. The regex is
 * applied to the joined token string (space-separated). Each matched
 * portion is replaced, then the result is split back into tokens.
 */
export class RegexCollapseNormalizer implements TokenNormalizer {
  readonly name = "regex-collapse";

  /**
   * @param patterns - Regex patterns and their replacements
   */
  constructor(
    private readonly patterns: ReadonlyArray<{
      /** Regex pattern to match in the joined token string */
      readonly regex: RegExp;
      /** Replacement string (use "" to remove) */
      readonly replacement: string;
    }>,
  ) {}

  // No learn phase needed — patterns are statically configured

  normalize(
    tokens: readonly string[],
    _paramStr: string,
  ): NormalizationResult {
    const changes: string[] = [];
    let joined = tokens.join(" ");

    for (const { regex, replacement } of this.patterns) {
      const before = joined;
      joined = joined.replace(regex, replacement);
      if (before !== joined) {
        changes.push(
          `collapsed pattern ${regex.source} → "${replacement}"`,
        );
      }
    }

    // Re-split, filtering empty tokens
    const result = joined
      .split(/\s+/)
      .filter((t) => t.length > 0);

    return { tokens: result, changes };
  }
}

// ============================================================
// Built-in: Adjacent Constant Fusion
// ============================================================

/**
 * Fuses adjacent constant tokens into compound tokens.
 *
 * ## Algorithm (Learn Phase)
 *
 * For the most common token length L in the batch:
 * 1. Filter to only messages of length L
 * 2. For each adjacent pair (i, i+1), check if BOTH tokens are:
 *    - Constant across ALL messages of length L
 *    - Content words (purely alphabetic, at least `minTokenLength` chars)
 *    - Not parameter placeholders (no `<` or `>`)
 * 3. Mark qualifying pairs for fusion
 *
 * ## Algorithm (Normalize Phase)
 *
 * 1. Only fuse if the message has the same token count as the learned pairs
 * 2. For each fusion pair, combine tokens with paramStr inserted between them
 * 3. Return the fused sequence
 *
 * ## Safety Guarantees
 *
 * - Only fuses tokens that are **demonstrably constant** across ALL messages
 * - Only applies to messages of the **same length** as the learned pairs
 * - Only fuses **content words** (no punctuation, no parameters)
 * - Each fusion **reduces** token count, improving cluster coherence
 *
 * ## Example: Proxifier
 *
 * Input (10 tokens):
 *   ["HOST", "close", "NUM", "bytes", "sent", "NUM", "bytes", "received", "lifetime", "DURATION"]
 *
 * Learned fusions: pos3+4 ("bytes"+"sent"), pos6+7 ("bytes"+"received")
 *
 * Output (8 tokens):
 *   ["HOST", "close", "NUM", "bytes<*>sent", "NUM", "bytes<*>received", "lifetime", "DURATION"]
 */
export class AdjacentConstantFusion implements TokenNormalizer {
  readonly name = "adjacent-constant-fusion";

  /**
   * @param minTokenLength - Minimum token length for content word detection (default: 2)
   * @param insertParamStr - Whether to insert paramStr between fused tokens (default: true)
   */
  constructor(
    private readonly minTokenLength: number = 2,
    private readonly insertParamStr: boolean = true,
  ) {}

  /**
   * Learned fusion pairs: Map of source position → destination position
   *
   * Each entry means: tokens[pos] and tokens[pos+1] should be fused.
   * Pairs are stored in descending order so fusing from back to front
   * doesn't affect earlier indices.
   */
  private fusionPositions: number[] = [];

  /**
   * The token length these fusion pairs apply to.
   * Messages of other lengths are not fused.
   */
  private applicableLength: number = 0;

  learn(messages: readonly (readonly string[])[]): void {
    if (messages.length < 2) return;

    // Find the most common token length
    const lengthCounts = new Map<number, number>();
    for (const msg of messages) {
      const len = msg.length;
      lengthCounts.set(len, (lengthCounts.get(len) ?? 0) + 1);
    }

    let maxCount = 0;
    let dominantLength = 0;
    for (const [len, count] of lengthCounts) {
      if (count > maxCount) {
        maxCount = count;
        dominantLength = len;
      }
    }

    // Need at least 2 messages of the same length to find constant pairs
    const sameLenMessages = messages.filter(
      (m) => m.length === dominantLength,
    );
    if (sameLenMessages.length < 2) return;

    this.applicableLength = dominantLength;
    this.fusionPositions = [];

    for (let i = 0; i < dominantLength - 1; i++) {
      const tokenI = sameLenMessages[0]![i]!;
      const tokenI1 = sameLenMessages[0]![i + 1]!;

      // Both tokens must be constant across all same-length messages
      const bothConstant = sameLenMessages.every(
        (m) => m[i] === tokenI && m[i + 1] === tokenI1,
      );

      if (!bothConstant) continue;

      // Both tokens must be content words (purely alphabetic)
      const isContentWord = (s: string): boolean => {
        return (
          s.length >= this.minTokenLength &&
          /^[a-zA-Z]+$/.test(s) &&
          !s.includes("<") &&
          !s.includes(">")
        );
      };

      if (isContentWord(tokenI) && isContentWord(tokenI1)) {
        this.fusionPositions.push(i);
        i++; // Skip next position to prevent overlapping fusion pairs
      }
    }

    // Sort descending so we can fuse from back to front without index shifts
    this.fusionPositions.sort((a, b) => b - a);
  }

  normalize(
    tokens: readonly string[],
    paramStr: string,
  ): NormalizationResult {
    // No learned fusions, or wrong length — pass through
    if (
      this.fusionPositions.length === 0 ||
      tokens.length !== this.applicableLength
    ) {
      return { tokens, changes: [] };
    }

    // Build fused token sequence
    const result = [...tokens];
    const changes: string[] = [];

    for (const pos of this.fusionPositions) {
      if (pos >= result.length - 1) continue;

      const left = result[pos]!;
      const right = result[pos + 1]!;

      const fused = this.insertParamStr
        ? `${left}${paramStr}${right}`
        : `${left}${right}`;

      result.splice(pos, 2, fused);
      changes.push(
        `fused tokens[${pos}]="${left}" + tokens[${pos + 1}]="${right}" → "${fused}"`,
      );
    }

    return { tokens: result, changes };
  }
}

// ============================================================
// Factory
// ============================================================

/**
 * Creates a default token normalizer pipeline (empty — no normalization).
 */
export function createDefaultNormalizerPipeline(): TokenNormalizerPipeline {
  return new TokenNormalizerPipeline();
}

/**
 * Creates a pipeline with AdjacentConstantFusion enabled.
 *
 * @param minTokenLength - Minimum alpha token length (default: 2)
 */
export function createExtendedNormalizerPipeline(
  minTokenLength: number = 2,
): TokenNormalizerPipeline {
  return new TokenNormalizerPipeline().register(
    new AdjacentConstantFusion(minTokenLength),
  );
}
